name: Test - Integration

on:
  push:
    branches:
      - "experimentlal/integration-test-deployment-workflow-2"
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip build and use reference artifacts'
        required: false
        default: 'true'
        type: choice
        options:
          - 'false'
          - 'true'
      reference_run_id:
        description: 'Reference run ID to download artifacts from (e.g., 12345678901)'
        required: false
        default: '17271306310'
        type: string

env:
  CACHE_SCOPE: deploy-synnax

jobs:
  build-ubuntu-22-04:
    name: Build Synnax (Ubuntu-22.04)
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    if: inputs.skip_build == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: deploy-synnax-ubuntu-22.04
          repository-cache: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: go.work.sum

      - name: Build Synnax (Ubuntu 22.04 - NI Linux RT)
        id: version
        run: echo "Ubuntu 22.04 build disabled - hardware not available"
        # run: integration/scripts/build-ubuntu-22-04.sh

      - name: Upload Driver Binary as Artifact
        uses: actions/upload-artifact@v4
        if: false  # Disabled until hardware available
        with:
          name: driver-nilinuxrt
          path: bazel-bin/driver/driver
          retention-days: 7

      - name: Upload Server Binary as Artifact
        uses: actions/upload-artifact@v4
        if: false  # Disabled until hardware is available
        with:
          name: synnax-server-nilinuxrt
          path: synnax/synnax-v${{ steps.version.outputs.VERSION }}-nilinuxrt
          retention-days: 7

      - name: Debug Build Environment
        if: failure()
        run: echo "Ubuntu 22.04 build debug disabled - hardware not available"
        # run: integration/scripts/debug-build-environment-ubuntu.sh

  build-ubuntu-latest:
    name: Build Synnax (ubuntu-latest)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: inputs.skip_build == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: deploy-synnax-ubuntu-latest
          repository-cache: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: go.work.sum

      - name: Build Synnax (Ubuntu Latest)
        id: version
        run: integration/scripts/build-ubuntu-latest.sh

      - name: Upload Driver Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: driver-linux
          path: bazel-bin/driver/driver
          retention-days: 7

      - name: Upload Server Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: synnax-server-linux
          path: synnax/synnax-v${{ steps.version.outputs.VERSION }}-linux
          retention-days: 7

      - name: Debug Build Environment
        if: failure()
        run: integration/scripts/debug-build-environment-ubuntu.sh

  build-windows-latest:
    name: Build Synnax (windows-latest)
    timeout-minutes: 60
    runs-on: windows-latest
    if: inputs.skip_build == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22000

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: deploy-synnax-windows-latest
          repository-cache: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: go.work.sum

      - name: Build Synnax (Windows Latest)
        id: version
        shell: cmd
        run: integration/scripts/build-windows-latest.cmd

      - name: Upload Driver Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: driver-windows
          path: bazel-bin/driver/driver.exe
          retention-days: 7

      - name: Upload Server Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: synnax-server-windows
          path: synnax/synnax-v${{ steps.version.outputs.VERSION }}-windows.exe
          retention-days: 7

      - name: Debug Build Environment
        if: failure()
        shell: cmd
        run: integration/scripts/debug-build-environment-windows.cmd

  build-macos-15:
    name: Build Synnax (macos-15)
    timeout-minutes: 60
    runs-on: macos-15
    if: inputs.skip_build == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: deploy-synnax-macos-15
          repository-cache: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: go.work.sum

      - name: Build Synnax (macOS)
        id: version
        run: echo "macOS build disabled - hardware not available"
        # run: integration/scripts/build-macos-15.sh

      - name: Upload Driver Binary as Artifact
        uses: actions/upload-artifact@v4
        if: false  # Disabled until hardware available
        with:
          name: driver-macos
          path: bazel-bin/driver/driver
          retention-days: 7

      - name: Upload Server Binary as Artifact
        uses: actions/upload-artifact@v4
        if: false  # Disabled until hardware available
        with:
          name: synnax-server-macos
          path: synnax/synnax-v${{ steps.version.outputs.VERSION }}-macos
          retention-days: 7

      - name: Debug Build Environment
        if: failure()
        run: echo "macOS build debug disabled - hardware not available"
        # run: integration/scripts/debug-build-environment-macos.sh

  download-artifacts-windows:
    name: Download Artifacts (Windows)
    timeout-minutes: 1
    runs-on:
      - self-hosted
      - windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Setup Windows Artifacts
        shell: cmd
        env:
          GH_TOKEN: ${{ github.token }}
          SKIP_BUILD: ${{ inputs.skip_build }}
          REFERENCE_RUN_ID: ${{ inputs.reference_run_id }}
        run: integration/scripts/download-artifacts-windows.cmd

  deploy-and-test-windows:
    name: Deploy and Test (windows)
    runs-on:
      - self-hosted
      - windows
    needs: download-artifacts-windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Force Quit Existing Synnax Processes (Windows)
        shell: cmd
        run: integration/scripts/kill-synnax-processes-windows.cmd

      - name: Install Poetry & Dependencies
        shell: powershell
        run: integration/scripts/install-poetry-deps-windows.ps1

      - name: Start Synnax Server
        timeout-minutes: 1
        shell: powershell
        run: integration/scripts/start-synnax-server-windows.ps1

      - name: Test Conductor
        id: test-conductor
        timeout-minutes: 5
        shell: powershell
        env:
          PYTHONIOENCODING: utf-8
        run: integration/scripts/run-test-conductor-windows.ps1

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: steps.test-conductor.outcome == 'success' || steps.test-conductor.outcome == 'failure'
        with:
          name: test-results-windows
          path: |
            integration/test/py/*.png
            integration/test/py/*.log
            integration/test/py/*.json
          retention-days: 30

      - name: Debug Test Environment
        if: failure()
        shell: powershell
        run: integration/scripts/debug-test-environment-windows.ps1

  download-artifacts-macos:
    name: Download Artifacts (macos)
    timeout-minutes: 1
    runs-on:
      - self-hosted
      - macos
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Setup macOS Artifacts
        env:
          GH_TOKEN: ${{ github.token }}
          SKIP_BUILD: ${{ inputs.skip_build }}
          REFERENCE_RUN_ID: ${{ inputs.reference_run_id }}
        run: echo "macOS artifacts setup disabled - hardware not available"
        # run: integration/scripts/download-artifacts-macos.sh

  deploy-and-test-macos:
    name: Deploy and Test (macos)
    runs-on:
      - self-hosted
      - macos
    needs: download-artifacts-macos
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Force Quit Existing Synnax Processes
        run: echo "macOS process cleanup disabled - hardware not available"
        # run: integration/scripts/kill-synnax-processes-macos.sh

      - name: Install Poetry & Dependencies
        run: echo "macOS Poetry installation disabled - hardware not available"
        # run: integration/scripts/install-poetry-deps-macos.sh

      - name: Start Synnax Server
        timeout-minutes: 1
        run: echo "macOS server startup disabled - hardware not available"
        # run: integration/scripts/start-synnax-server-macos.sh

      - name: Test Conductor
        id: test-conductor
        timeout-minutes: 5
        run: echo "macOS test conductor disabled - hardware not available"
        # run: integration/scripts/run-test-conductor-macos.sh

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: false  # Disabled until hardware available
        with:
          name: test-results-macos
          path: |
            integration/test/py/*.png
            integration/test/py/*.log
            integration/test/py/*.json
          retention-days: 30

      - name: Debug Test Environment
        if: failure()
        run: echo "macOS debug disabled - hardware not available"
        # run: integration/scripts/debug-test-environment-macos.sh

  download-artifacts-linux:
    name: Download Artifacts (Linux)
    timeout-minutes: 1
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Setup Linux Artifacts
        env:
          GH_TOKEN: ${{ github.token }}
          SKIP_BUILD: ${{ inputs.skip_build }}
          REFERENCE_RUN_ID: ${{ inputs.reference_run_id }}
        run: integration/scripts/download-artifacts-linux.sh

  deploy-and-test-linux:
    name: Deploy and Test (linux)
    runs-on:
      - self-hosted
      - Linux
    needs: download-artifacts-linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Force Quit Existing Synnax Processes
        run: integration/scripts/kill-synnax-processes-linux.sh

      - name: Install Poetry & Dependencies
        run: integration/scripts/install-poetry-deps-linux.sh

      - name: Start Synnax Server
        timeout-minutes: 1
        run: integration/scripts/start-synnax-server-linux.sh

      - name: Test Conductor
        id: test-conductor
        timeout-minutes: 5
        run: integration/scripts/run-test-conductor-linux.sh

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: steps.test-conductor.outcome == 'success' || steps.test-conductor.outcome == 'failure'
        with:
          name: test-results-linux
          path: |
            integration/test/py/*.png
            integration/test/py/*.log
            integration/test/py/*.json
          retention-days: 30

      - name: Debug Test Environment
        if: failure()
        run: integration/scripts/debug-test-environment-linux.sh